In [1]:
import os
import numpy as np
import pandas as pd
import shutil
from tqdm import tqdm_notebook
import datetime
from dateutil.relativedelta import relativedelta

In [ ]:
universe = pd.ExcelFile('../../../Private/Data_source/universe.xlsm')#Reading universe 
metrics = universe.sheet_names#List the metrics
data_metrics = {metric : pd.read_excel('../../../Private/Data_source/universe.xlsm', sheet_name=metric) for metric in metrics}
data_metrics = {metric : data_metrics[metric].dropna(axis=1) for metric in metrics}
groups = list(set([elem for metric in data_metrics for elem in data_metrics[metric]['group'].unique()]))

In [5]:
dates = pd.read_csv('../../../Public/faang/revenue/faang_revenue_Level_CSV/BLX_faang_revenue_index_level_data.csv'.replace(' ','_'))
ss  = pd.DataFrame()
ss['Date'] = dates['Date']
for group in groups :
    for metric in metrics :
        try :
            Level = pd.read_csv('../../../Public/{0}/{1}/{0}_{1}_Level_CSV/BLX_{0}_{1}_index_level_data.csv'.format(group,metric).replace(' ','_'))  
        except :
            continue
        name = '{0}_{1}'.format(group, metric)
        ss[name] = Level['Index Level']
            
ss.to_csv('fact sheet content.csv')

In [46]:
##########################################

In [47]:
def compute_annualized(EB, BB, n) :
    return pow((EB/BB), 1/n) - 1

def ss_most_recent(df, month_delta) :
    last_recent = df['Date'].loc[len(df) - 1] - relativedelta(months=month_delta)
    return df[df['Date'] > last_recent]

In [48]:
ss = pd.read_csv('fact sheet content.csv', index_col=0)
ss['Date'] = ss['Date'].apply(lambda date : datetime.datetime.strptime(date, '%Y-%m-%d')) # convert date string to datetime

# year to date return
actual_year = ss['Date'].loc[len(ss)-1].year 
ss_actual_year = ss[[date.year == actual_year for date in ss['Date']]] 

# most recent 1, 3, 6 months and 1, 3 5 years returns
months_delta = [1, 3, 6, 12, 36, 60]
dfs = [ss_most_recent(ss, month_delta) for month_delta in months_delta]

In [49]:
key_data_names = ['YTD_Return', 'Ann_1_Month', 'Ann_3_Months', 'Ann_6_Months', 'Ann_1_Year', 'Ann_3_Years', 'Ann_5_Years', 'Ann_Inception']
new_ss = pd.DataFrame()
new_ss['key_data_names'] = key_data_names

group_metrics = [group_metric for group_metric in ss if group_metric != 'Date']
for group_metric in group_metrics :
    EB, BB, n = ss_actual_year[group_metric].iloc[-1], ss_actual_year[group_metric].iloc[0], 1 # duration_days/365 (if annualized)
    key_data_val = [compute_annualized(EB, BB, n)]
    
    for i in range(len(dfs)) :
        month_delta = months_delta[i]
        df = dfs[i]
        EB, BB, n = df[group_metric].iloc[-1], df[group_metric].iloc[0], month_delta/12
        if month_delta <= 12 :
            n=1
        key_data_val.append(compute_annualized(EB, BB, n))
    start_date, end_date = ss['Date'].iloc[0], ss['Date'].iloc[-1]
    duration_days = (end_date - start_date).days
    EB, BB, n = ss[group_metric].iloc[-1], ss[group_metric].iloc[0], duration_days/365
    key_data_val.append(compute_annualized(EB, BB, n))
    new_ss[group_metric] = key_data_val

<ipython-input-47-7bd8e594d0e4>:2: RuntimeWarning: invalid value encountered in double_scalars
  return pow((EB/BB), 1/n) - 1

In [50]:
new_ss.to_csv('finale_result.csv')

In [51]:
new_ss

,key_data_names,mining & metals_revenue,natural resources_revenue,saas_revenue,saas_earnings,saas_margin,saas_operating income,airline_wallstreet revenue estimate,airline_revenue,airline_earnings,...,asset manager_revenue,asset manager_earnings,asset manager_margin,asset manager_ebitda,faang_wallstreet revenue estimate,faang_revenue,faang_earnings,faang_margin,faang_ebitda,faang_operating income
0,YTD_Return,-0.083071,-0.158816,0.055547,0.076351,18.755317,0.054969,-0.568430,-0.254690,-1.624048,...,-0.083072,-0.840638,-2.889038,-0.350378,-0.030831,0.121848,0.090056,335.813056,0.122014,0.094298
1,Ann_1_Month,-0.048713,-0.125785,0.015158,-0.042975,14.040593,0.011199,0.000000,-0.183277,-75.646225,...,0.007736,-24.759074,0.722132,-0.018085,0.000000,0.039347,0.027013,316.538463,-0.005505,0.019544
2,Ann_3_Months,-0.051049,-0.126421,0.013321,-0.046451,15.891790,0.008026,-0.077040,-0.233373,-2.181264,...,0.007599,51.343018,0.761583,-0.018198,-0.000348,0.040890,0.030692,321.874390,-0.000938,0.024126
3,Ann_6_Months,-0.085336,-0.148175,0.036587,-0.005171,16.456607,0.012086,-0.566756,-0.260181,-1.615625,...,-0.112986,-0.882877,-2.191684,-0.367039,-0.040123,0.073090,0.044670,331.203751,0.097314,0.049102
4,Ann_1_Year,-0.110999,-0.176301,0.082016,0.106180,19.951680,0.073967,-0.573109,-0.247116,-1.661261,...,-0.076172,-0.849122,-2.398249,-0.340992,-0.023129,0.162628,0.071138,325.959776,0.175775,0.105688
5,Ann_3_Years,0.027989,0.012500,0.093438,0.176509,2.146729,0.157330,-0.195242,-0.053012,NaN,...,0.086808,-0.496456,NaN,0.005550,0.194155,0.184892,0.166745,5.855548,0.158174,0.131035
6,Ann_5_Years,-0.013965,-0.040997,0.060163,0.156961,1.140935,0.095530,-0.114154,-0.023289,NaN,...,0.055452,-0.382757,NaN,0.024606,0.164878,0.159449,0.135068,2.336321,0.138988,0.102810
7,Ann_Inception,-0.014395,-0.061718,0.049036,0.058847,0.698007,0.040638,-0.069498,0.003358,NaN,...,0.071094,-0.329238,NaN,0.159433,0.168706,0.164498,0.151624,1.542251,0.161621,0.130724

In [45]:
true = pd.read_csv('true_results.csv', index_col=0)
true

,mining & metals_revenue,natural resources_revenue,faang_wallstreet revenue estimate,faang_revenue,faang_earnings,faang_ebitda,faang_operating income,select bank_wallstreet revenue estimate,select bank_revenue,select bank_earnings,...,cable_ebitda,cable_operating income,clean energy_revenue,clean energy_earnings,saas_revenue,saas_earnings,saas_operating income,airline_wallstreet revenue estimate,airline_revenue,airline_earnings
key_data_names,,,,,,,,,,,,,,,,,,,,,
YTD_Return,-8.3%,-15.9%,-3.1%,12.2%,9.0%,12.2%,9.4%,-3.3%,-2.6%,-26.1%,...,1.4%,2.3%,6.4%,-249.8%,5.6%,7.6%,5.5%,-56.8%,-25.5%,NaN
1_Month,-4.9%,-12.6%,0.0%,3.9%,2.7%,-0.6%,2.0%,0.0%,-1.7%,-13.1%,...,0.4%,0.7%,-9.9%,-4.2%,1.5%,-4.3%,1.1%,0.0%,-18.3%,NaN
3_Months,-5.1%,-12.6%,0.0%,4.1%,3.1%,-0.1%,2.4%,0.7%,-1.7%,-13.1%,...,0.4%,0.6%,-9.8%,-3.8%,1.3%,-5.0%,0.4%,-7.7%,-23.3%,NaN
6_Months,-8.5%,-15.2%,-4.1%,7.3%,4.5%,9.7%,4.9%,-4.2%,-2.4%,-25.8%,...,0.0%,-0.6%,4.5%,-367.5%,3.7%,-0.5%,1.2%,-56.7%,-26.0%,NaN
1_Year,-11.1%,-17.6%,-2.3%,16.3%,7.1%,17.6%,10.6%,-3.8%,-1.3%,-27.6%,...,2.8%,4.3%,5.3%,-233.9%,8.2%,10.6%,7.4%,-57.3%,-24.7%,NaN
Ann_3_Years,2.8%,1.2%,19.4%,18.5%,16.7%,15.8%,13.1%,-1.6%,5.8%,-2.4%,...,5.9%,6.1%,-0.7%,-174.6%,9.3%,17.7%,15.7%,-19.5%,-5.3%,NaN
Ann_5_Years,-1.4%,-4.1%,16.5%,15.9%,13.5%,13.9%,10.3%,0.1%,4.6%,1.7%,...,9.6%,7.7%,-0.3%,11.0%,6.0%,15.7%,9.6%,-11.4%,-2.3%,NaN
Ann_Inception,-1.6%,-6.6%,18.3%,17.9%,16.5%,17.6%,14.2%,-0.3%,3.5%,2.9%,...,6.5%,8.0%,-0.3%,1.8%,5.3%,6.4%,4.4%,-7.5%,0.4%,NaN